steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/kitchensink-repo/kitchensink:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/kitchensink-repo/kitchensink:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'kitchensink-app'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/kitchensink-repo/kitchensink:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
